name: sanity
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - name: Run sanity checks
        run: make vendor && make lint && make diff
